// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using limeify_be;

#nullable disable

namespace limeify_be.Migrations
{
    [DbContext(typeof(LimeifyDbContext))]
    partial class LimeifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Limeify.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Albums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            GenreId = 1,
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/9b/Tame_Impala_-_Currents.png",
                            Name = "Currents",
                            Year = 2015
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            GenreId = 1,
                            Image = "https://t2.genius.com/unsafe/383x0/https%3A%2F%2Fimages.genius.com%2F5f9a6674593806ac72677141c0e66330.1000x1000x1.png",
                            Name = "Father of the Bride",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            GenreId = 1,
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/23/Phoebe_Bridgers_Punisher_%282020%29.png",
                            Name = "Punisher",
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            GenreId = 2,
                            Image = "https://upload.wikimedia.org/wikipedia/en/e/e3/Luke_Combs_-_What_You_See_Is_What_You_Get.png",
                            Name = "What You See Is What You Get",
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 5,
                            GenreId = 2,
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/Carrie_Underwood_-_Cry_Pretty_%28Official_Album_Cover%29.png/220px-Carrie_Underwood_-_Cry_Pretty_%28Official_Album_Cover%29.png",
                            Name = "Cry Pretty",
                            Year = 2018
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 6,
                            GenreId = 2,
                            Image = "https://upload.wikimedia.org/wikipedia/en/6/65/Kacey_Musgraves_-_Golden_Hour.png",
                            Name = "Golden Hour",
                            Year = 2018
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 7,
                            GenreId = 3,
                            Image = "https://upload.wikimedia.org/wikipedia/en/c/c5/Southeasternjasonisbell.jpg",
                            Name = "Southeastern",
                            Year = 2013
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 8,
                            GenreId = 3,
                            Image = "https://upload.wikimedia.org/wikipedia/en/1/18/The_Carpenter_%28The_Avett_Brothers%29_cover_art.jpg",
                            Name = "The Carpenter",
                            Year = 2012
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 9,
                            GenreId = 3,
                            Image = "https://upload.wikimedia.org/wikipedia/en/e/ec/By_the_Way%2C_I_Forgive_You_-_Brandi_Carlile.png",
                            Name = "By the Way, I Forgive You",
                            Year = 2018
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 10,
                            GenreId = 4,
                            Image = "https://upload.wikimedia.org/wikipedia/en/f/f6/Taylor_Swift_-_1989.png",
                            Name = "1989",
                            Year = 2014
                        },
                        new
                        {
                            Id = 11,
                            ArtistId = 11,
                            GenreId = 4,
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a0/Ariana_Grande_-_Positions.png",
                            Name = "Positions",
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            ArtistId = 12,
                            GenreId = 4,
                            Image = "https://upload.wikimedia.org/wikipedia/en/f/f5/Dua_Lipa_-_Future_Nostalgia_%28Official_Album_Cover%29.png",
                            Name = "Future Nostalgia",
                            Year = 2020
                        },
                        new
                        {
                            Id = 13,
                            ArtistId = 13,
                            GenreId = 5,
                            Image = "https://upload.wikimedia.org/wikipedia/en/b/b2/Metallica_-_Master_of_Puppets_cover.jpg",
                            Name = "Master of Puppets",
                            Year = 1986
                        },
                        new
                        {
                            Id = 14,
                            ArtistId = 14,
                            GenreId = 5,
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/IronMaiden_NumberOfBeast.jpg/220px-IronMaiden_NumberOfBeast.jpg",
                            Name = "The Number of the Beast",
                            Year = 1982
                        },
                        new
                        {
                            Id = 15,
                            ArtistId = 15,
                            GenreId = 5,
                            Image = "https://upload.wikimedia.org/wikipedia/en/1/1d/Slipknot_Iowa.jpg",
                            Name = "Iowa",
                            Year = 2001
                        },
                        new
                        {
                            Id = 16,
                            ArtistId = 16,
                            GenreId = 6,
                            Image = "https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png",
                            Name = "To Pimp a Butterfly",
                            Year = 2015
                        },
                        new
                        {
                            Id = 17,
                            ArtistId = 17,
                            GenreId = 6,
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/90/Scorpion_by_Drake.jpg",
                            Name = "Scorpion",
                            Year = 2018
                        },
                        new
                        {
                            Id = 18,
                            ArtistId = 18,
                            GenreId = 6,
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2a/2014ForestHillsDrive.jpg",
                            Name = "2014 Forest Hills Drive",
                            Year = 2014
                        },
                        new
                        {
                            Id = 19,
                            ArtistId = 19,
                            GenreId = 7,
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/2c/The_Blueprint.png",
                            Name = "The Blueprint",
                            Year = 2001
                        },
                        new
                        {
                            Id = 20,
                            ArtistId = 20,
                            GenreId = 7,
                            Image = "https://i.pinimg.com/736x/91/06/66/910666f35cc2c190e585bdda709567fc.jpg",
                            Name = "Queen",
                            Year = 2018
                        },
                        new
                        {
                            Id = 21,
                            ArtistId = 21,
                            GenreId = 7,
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/97/Cardi_B_-_Invasion_of_Privacy.png",
                            Name = "Invasion of Privacy",
                            Year = 2018
                        },
                        new
                        {
                            Id = 22,
                            ArtistId = 22,
                            GenreId = 8,
                            Image = "https://upload.wikimedia.org/wikipedia/en/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png",
                            Name = "Lemonade",
                            Year = 2016
                        },
                        new
                        {
                            Id = 23,
                            ArtistId = 23,
                            GenreId = 8,
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/The_Weeknd_-_After_Hours.png/220px-The_Weeknd_-_After_Hours.png",
                            Name = "After Hours",
                            Year = 2020
                        },
                        new
                        {
                            Id = 24,
                            ArtistId = 24,
                            GenreId = 8,
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg",
                            Name = "Blonde",
                            Year = 2016
                        },
                        new
                        {
                            Id = 25,
                            ArtistId = 25,
                            GenreId = 9,
                            Image = "https://upload.wikimedia.org/wikipedia/en/b/ba/Radioheadokcomputer.png",
                            Name = "OK Computer",
                            Year = 1997
                        },
                        new
                        {
                            Id = 26,
                            ArtistId = 26,
                            GenreId = 9,
                            Image = "https://upload.wikimedia.org/wikipedia/en/1/17/The_Killers_-_Hot_Fuss.png",
                            Name = "Hot Fuss",
                            Year = 2004
                        },
                        new
                        {
                            Id = 27,
                            ArtistId = 27,
                            GenreId = 9,
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/81/Arcade_Fire_-_The_Suburbs.jpg",
                            Name = "The Suburbs",
                            Year = 2010
                        },
                        new
                        {
                            Id = 28,
                            ArtistId = 28,
                            GenreId = 10,
                            Image = "https://m.media-amazon.com/images/I/81m8mrMsfAL._UF1000,1000_QL80_.jpg",
                            Name = "Ramones",
                            Year = 1976
                        },
                        new
                        {
                            Id = 29,
                            ArtistId = 29,
                            GenreId = 10,
                            Image = "https://upload.wikimedia.org/wikipedia/en/4/4b/Green_Day_-_Dookie_cover.jpg",
                            Name = "Dookie",
                            Year = 1994
                        },
                        new
                        {
                            Id = 30,
                            ArtistId = 30,
                            GenreId = 10,
                            Image = "https://upload.wikimedia.org/wikipedia/en/0/00/TheClashLondonCallingalbumcover.jpg",
                            Name = "London Calling",
                            Year = 1979
                        },
                        new
                        {
                            Id = 31,
                            ArtistId = 31,
                            GenreId = 11,
                            Image = "https://upload.wikimedia.org/wikipedia/en/e/ea/Blackparadecover.jpg",
                            Name = "The Black Parade",
                            Year = 2006
                        },
                        new
                        {
                            Id = 32,
                            ArtistId = 32,
                            GenreId = 11,
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Brand_New_Deja_Entendu.jpg/220px-Brand_New_Deja_Entendu.jpg",
                            Name = "Deja Entendu",
                            Year = 2003
                        },
                        new
                        {
                            Id = 33,
                            ArtistId = 33,
                            GenreId = 11,
                            Image = "https://upload.wikimedia.org/wikipedia/en/0/00/Fall_Out_Boy_-_From_Under_the_Cork_Tree_-_CD_album_cover.jpg",
                            Name = "From Under the Cork Tree",
                            Year = 2005
                        },
                        new
                        {
                            Id = 34,
                            ArtistId = 34,
                            GenreId = 12,
                            Image = "https://upload.wikimedia.org/wikipedia/en/4/4b/My_Bloody_Valentine_-_Loveless.png",
                            Name = "Loveless",
                            Year = 1991
                        },
                        new
                        {
                            Id = 35,
                            ArtistId = 35,
                            GenreId = 12,
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a6/Souvlaki_%28album%29_cover.jpg",
                            Name = "Souvlaki",
                            Year = 1993
                        },
                        new
                        {
                            Id = 36,
                            ArtistId = 36,
                            GenreId = 12,
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/9b/Nowhereridecover.jpg",
                            Name = "Nowhere",
                            Year = 1990
                        },
                        new
                        {
                            Id = 37,
                            ArtistId = 37,
                            GenreId = 13,
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/American_football_band_lp_cover.png/220px-American_football_band_lp_cover.png",
                            Name = "American Football",
                            Year = 1999
                        },
                        new
                        {
                            Id = 38,
                            ArtistId = 38,
                            GenreId = 13,
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/For_Long_Tomorrow.jpg/220px-For_Long_Tomorrow.jpg",
                            Name = "For Long Tomorrow",
                            Year = 2009
                        },
                        new
                        {
                            Id = 39,
                            ArtistId = 39,
                            GenreId = 13,
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/8f/Animals_%28This_Town_Needs_Guns_album%29.jpeg",
                            Name = "Animals",
                            Year = 2008
                        },
                        new
                        {
                            Id = 40,
                            ArtistId = 40,
                            GenreId = 14,
                            Image = "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcT9kry1myZTi2dMJ7OtgJjmdT__lImpI-pJ9mdq42Cz8HhIet_ro_Obp6q4xbksBbpT",
                            Name = "The Dark Side of the Moon",
                            Year = 1973
                        },
                        new
                        {
                            Id = 41,
                            ArtistId = 41,
                            GenreId = 14,
                            Image = "https://upload.wikimedia.org/wikipedia/en/0/09/Yes-close.jpg",
                            Name = "Close to the Edge",
                            Year = 1972
                        },
                        new
                        {
                            Id = 42,
                            ArtistId = 42,
                            GenreId = 14,
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/84/In_the_Court_of_the_Crimson_King_-_40th_Anniversary_Box_Set_-_Front_cover.jpeg",
                            Name = "In the Court of the Crimson King",
                            Year = 1969
                        },
                        new
                        {
                            Id = 43,
                            ArtistId = 43,
                            GenreId = 15,
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Ninth_Symphony_original.png/1200px-Ninth_Symphony_original.png",
                            Name = "Symphony No. 9",
                            Year = 1824
                        },
                        new
                        {
                            Id = 44,
                            ArtistId = 44,
                            GenreId = 15,
                            Image = "https://upload.wikimedia.org/wikipedia/commons/3/3e/Mozart_magic_flute.jpg",
                            Name = "The Magic Flute",
                            Year = 1791
                        },
                        new
                        {
                            Id = 45,
                            ArtistId = 45,
                            GenreId = 15,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDbK128Dg3CQyAyUSp-wgXsA4gfSSTYxFf0g&s",
                            Name = "The Well-Tempered Clavier",
                            Year = 1722
                        });
                });

            modelBuilder.Entity("Limeify.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Tame Impala is the psychedelic music project led by Australian multi-instrumentalist Kevin Parker.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2019/05/tame-impala-lead-photo.jpg?w=1600&h=900&crop=1",
                            Name = "Tame Impala"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Vampire Weekend is an American indie rock band known for blending baroque pop, African influences, and indie rock.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2018/06/vampire-weekend-debut-album-abcc4ca0-a4df-4c7b-95ca-ad447c4142d2.jpg",
                            Name = "Vampire Weekend"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Phoebe Bridgers is an American indie singer-songwriter known for her introspective lyrics and haunting voice.",
                            Image = "https://ca-times.brightspotcdn.com/dims4/default/ac37e6d/2147483647/strip/false/crop/3492x2298+0+0/resize/1486x978!/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F03%2F3d%2Fe3ef1ead45349f30c310a1554d3d%2Fhttps-delivery.gettyimages.com%2Fdownloads%2F1270300100",
                            Name = "Phoebe Bridgers"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Luke Combs is an American country singer-songwriter who has achieved rapid success with a blend of modern and traditional country sounds.",
                            Image = "https://resources.tidal.com/images/72cb8594/f5c6/41c2/be8d/b4ef5152baef/750x750.jpg",
                            Name = "Luke Combs"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Carrie Underwood is a country music icon known for her powerful voice and chart-topping hits.",
                            Image = "https://amp.nbc.com/sites/nbcblog/files/2023/10/carrie-underwood.jpg",
                            Name = "Carrie Underwood"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Kacey Musgraves is a Grammy-winning country artist whose music bridges traditional and modern influences.",
                            Image = "https://static.stereogum.com/uploads/2019/01/GettyImages-1080542124-1548878332-1000x667.jpg",
                            Name = "Kacey Musgraves"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Jason Isbell is an Americana artist known for his powerful songwriting and contributions to modern southern rock.",
                            Image = "https://i8.amplience.net/i/naras/jason-isbell_MI0004810104-MN0000562615",
                            Name = "Jason Isbell"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "The Avett Brothers are a folk rock band whose music combines bluegrass, country, and punk influences.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-13745-20131210-avett-x1800-1386694348.jpg",
                            Name = "The Avett Brothers"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Brandi Carlile is an acclaimed Americana artist known for her emotive voice and genre-spanning songwriting.",
                            Image = "https://dgpuo8cwvztoe.cloudfront.net/uploads/_f_lg/brandi_carlile-Mary-Ellen-Matthews.jpg",
                            Name = "Brandi Carlile"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Taylor Swift is an American singer-songwriter whose career has spanned country, pop, and alternative genres.",
                            Image = "https://deadline.com/wp-content/uploads/2024/10/Taylor-Swift-2170709912.jpg?w=681&h=383&crop=1",
                            Name = "Taylor Swift"
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Ariana Grande is a pop superstar known for her powerful vocals and chart-topping hits.",
                            Image = "https://www.billboard.com/wp-content/uploads/2022/08/Ariana-Grande-the-voice-2021-billboard-1548.jpg?w=1024",
                            Name = "Ariana Grande"
                        },
                        new
                        {
                            Id = 12,
                            Bio = "Dua Lipa is a British pop sensation known for her disco-inspired sound and dance-pop hits.",
                            Image = "https://media.gq.com/photos/5a5f79d835be9e1aebeceecf/4:3/w_4556,h_3417,c_limit/Dua_Lipa_01.jpg",
                            Name = "Dua Lipa"
                        },
                        new
                        {
                            Id = 13,
                            Bio = "Metallica is a legendary heavy metal band known for their aggressive sound and influence on the genre.",
                            Image = "https://northernvirginiamag.com/wp-content/uploads/2024/09/metallica1_ross_halfin_photographer-copy.webp",
                            Name = "Metallica"
                        },
                        new
                        {
                            Id = 14,
                            Bio = "Iron Maiden is a British heavy metal band known for their elaborate stage shows and complex compositions.",
                            Image = "https://www.ironmaiden.com/files/2024/08/WS_2023_Lineup.jpg",
                            Name = "Iron Maiden"
                        },
                        new
                        {
                            Id = 15,
                            Bio = "Slipknot is an American heavy metal band known for their intense live performances and masked personas.",
                            Image = "https://i.scdn.co/image/ab6761610000e5ebd0cdb283a7384a0edb665182",
                            Name = "Slipknot"
                        },
                        new
                        {
                            Id = 16,
                            Bio = "Kendrick Lamar is a Pulitzer Prize-winning rapper known for his socially conscious lyrics and innovative sound.",
                            Image = "https://variety.com/wp-content/uploads/2017/11/kendrick-lamar-variety-hitmakers.jpg?w=1000&h=562&crop=1",
                            Name = "Kendrick Lamar"
                        },
                        new
                        {
                            Id = 17,
                            Bio = "Drake is a Canadian rapper and singer whose music blends rap, R&B, and pop influences.",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQstSLn_yCOFPQ66fJ17gyaUpHsuE_l3dLNow&s",
                            Name = "Drake"
                        },
                        new
                        {
                            Id = 18,
                            Bio = "J. Cole is an American rapper and producer known for his introspective lyrics and storytelling ability.",
                            Image = "https://i1.sndcdn.com/avatars-CkLqCmTeMPSVzN50-GiKLzA-t1080x1080.jpg",
                            Name = "J. Cole"
                        },
                        new
                        {
                            Id = 19,
                            Bio = "Jay-Z is a hip hop mogul and one of the most influential rappers of all time.",
                            Image = "https://people.com/thmb/Im3tORdvaReCzwJDAZyvzhCTNb4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(704x369:706x371)/jay-z-edf6090ede3c4547a47da0cf9c633778.jpg",
                            Name = "Jay-Z"
                        },
                        new
                        {
                            Id = 20,
                            Bio = "Nicki Minaj is a hip hop and pop artist known for her bold personality and genre-bending hits.",
                            Image = "https://media.npr.org/assets/img/2023/09/01/minaj_custom-b03a0992f23b6fe5d3d5add53c8920cd1b7e0c42.jpg",
                            Name = "Nicki Minaj"
                        },
                        new
                        {
                            Id = 21,
                            Bio = "Cardi B is a Grammy-winning rapper known for her energetic performances and charismatic personality.",
                            Image = "https://globalnews.ca/wp-content/uploads/2023/07/GettyImages-1512301113.jpg?quality=85&strip=all&w=1200",
                            Name = "Cardi B"
                        },
                        new
                        {
                            Id = 22,
                            Bio = "Beyoncé is a global superstar and one of the most influential R&B artists of her generation.",
                            Image = "https://media.glamour.com/photos/5cb7a1bf79e625ccc25b462c/master/pass/GettyImages-946416208.jpg",
                            Name = "Beyoncé"
                        },
                        new
                        {
                            Id = 23,
                            Bio = "The Weeknd is a Canadian R&B singer known for his moody sound and chart-topping hits.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2020/02/THE-WEEKND-by-Duncan-Loudon.jpg?w=1581&h=1054&crop=1",
                            Name = "The Weeknd"
                        },
                        new
                        {
                            Id = 24,
                            Bio = "Frank Ocean is an American singer-songwriter whose music combines R&B, soul, and alternative influences.",
                            Image = "https://www.hollywoodinsider.com/wp-content/uploads/2020/09/Hollywood-Insider-Frank-Ocean-Letter-From-Fan.jpg",
                            Name = "Frank Ocean"
                        },
                        new
                        {
                            Id = 25,
                            Bio = "Radiohead is a British alternative rock band known for their experimental sound and boundary-pushing music.",
                            Image = "https://images.bauerhosting.com/marketing/sites/16/2023/05/Radiohead-1995-hero.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=undefined&q=80",
                            Name = "Radiohead"
                        },
                        new
                        {
                            Id = 26,
                            Bio = "The Killers are an American rock band whose music blends alternative rock, new wave, and synth-pop.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2024/08/Photo-3-202106_The-Killers4981_no91_no6.jpg?w=1581&h=1054&crop=1",
                            Name = "The Killers"
                        },
                        new
                        {
                            Id = 27,
                            Bio = "Arcade Fire is a Canadian indie rock band known for their ambitious albums and eclectic sound.",
                            Image = "https://i.guim.co.uk/img/media/da207ed976e1b316bab8a8ae547b6dbdc992911f/504_0_4674_2805/master/4674.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=0f625bcdff3a9aede290d4cfa832dcfa",
                            Name = "Arcade Fire"
                        },
                        new
                        {
                            Id = 28,
                            Bio = "The Ramones were a pioneering American punk rock band known for their fast, stripped-down sound.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-226789-BPW2FR.jpg?w=1581&h=1054&crop=1",
                            Name = "The Ramones"
                        },
                        new
                        {
                            Id = 29,
                            Bio = "Green Day is an American punk rock band that brought punk back to the mainstream in the 1990s.",
                            Image = "https://media.npr.org/assets/img/2024/01/29/green_day_hires-13_alice-baxley-applemusic-ef3e58054af3256bb65e4790038cb245758a6898.jpg",
                            Name = "Green Day"
                        },
                        new
                        {
                            Id = 30,
                            Bio = "The Sex Pistols were a British punk rock band known for their rebellious attitude and provocative music.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-183232-85094733.jpg?w=1581&h=1054&crop=1",
                            Name = "Sex Pistols"
                        },
                        new
                        {
                            Id = 31,
                            Bio = "My Chemical Romance is an American rock band known for their emo and punk-inspired sound.",
                            Image = "https://m.media-amazon.com/images/M/MV5BYmQwMTM1MTgtNDBhMy00ODY4LWFjOWItYzU4MGZkNmNhYzNiXkEyXkFqcGc@._V1_.jpg",
                            Name = "My Chemical Romance"
                        },
                        new
                        {
                            Id = 32,
                            Bio = "Dashboard Confessional is an American emo band known for their heartfelt lyrics and acoustic sound.",
                            Image = "https://www.billboard.com/wp-content/uploads/media/Dashboard-Confessional-2020-cr-Dave-Bean-billboard-1548.jpg?w=1024",
                            Name = "Dashboard Confessional"
                        },
                        new
                        {
                            Id = 33,
                            Bio = "Fall Out Boy is an American rock band known for their blend of pop-punk, emo, and alternative rock.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-179980-461150986.jpg?w=1581&h=1054&crop=1",
                            Name = "Fall Out Boy"
                        },
                        new
                        {
                            Id = 34,
                            Bio = "My Bloody Valentine is an Irish-English band credited with pioneering the shoegaze genre with their swirling guitar effects.",
                            Image = "https://d94thh4m1x8qv.cloudfront.net/eyJidWNrZXQiOiJkaXktbWFnYXppbmUiLCJrZXkiOiJkL2RpeS9BcnRpc3RzL00vTXktQmxvb2R5LVZhbGVudGluZS9QcmVzcy1zaG90LTIuanBnIiwiZWRpdHMiOnsianBlZyI6eyJxdWFsaXR5IjoxMDAsInByb2dyZXNzaXZlIjp0cnVlLCJ0cmVsbGlzUXVhbnRpc2F0aW9uIjp0cnVlLCJvdmVyc2hvb3REZXJpbmdpbmciOnRydWUsIm9wdGltaXplU2NhbnMiOnRydWV9LCJyZXNpemUiOnsid2lkdGgiOjE1MDAsImhlaWdodCI6MTAwMCwiZml0IjoiY292ZXIifX19",
                            Name = "My Bloody Valentine"
                        },
                        new
                        {
                            Id = 35,
                            Bio = "Slowdive is a British shoegaze band known for their atmospheric sound and lush guitar textures.",
                            Image = "https://heights-photos.s3.amazonaws.com/wp-content/uploads/2023/09/08003435/unnamed-1145x628.jpg",
                            Name = "Slowdive"
                        },
                        new
                        {
                            Id = 36,
                            Bio = "Ride is an English shoegaze band whose blend of noise rock and ethereal vocals defined the genre's early years.",
                            Image = "https://media.pitchfork.com/photos/592c55e70c2bba1b7de04698/master/pass/57dd23b1.jpg",
                            Name = "Ride"
                        },
                        new
                        {
                            Id = 37,
                            Bio = "American Football is a band that blends math rock's technicality with the emotional depth of emo.",
                            Image = "https://media.npr.org/assets/img/2016/10/11/americanfootballshervinlainezpress_wide-2fd88fc6a0049eb368b81d7ca0fed85bc55d1c2e.jpg",
                            Name = "American Football"
                        },
                        new
                        {
                            Id = 38,
                            Bio = "Toe is a Japanese instrumental math rock band known for their intricate rhythms and emotive performances.",
                            Image = "https://f4.bcbits.com/img/0004501051_10.jpg",
                            Name = "Toe"
                        },
                        new
                        {
                            Id = 39,
                            Bio = "TTNG is a British math rock band known for their complex guitar work and shifting time signatures.",
                            Image = "https://lastfm.freetls.fastly.net/i/u/ar0/066981738de4463080c3a02cc1bba55e.jpg",
                            Name = "TTNG (This Town Needs Guns)"
                        },
                        new
                        {
                            Id = 40,
                            Bio = "Pink Floyd is an iconic British progressive rock band known for their concept albums and psychedelic sound.",
                            Image = "https://i.scdn.co/image/d011c95081cd9a329e506abd7ded47535d524a07",
                            Name = "Pink Floyd"
                        },
                        new
                        {
                            Id = 41,
                            Bio = "Yes is a British prog rock band known for their complex compositions and virtuosic musicianship.",
                            Image = "https://www.udiscovermusic.com/wp-content/uploads/2020/04/Yes-GettyImages-107731098-1.png",
                            Name = "Yes"
                        },
                        new
                        {
                            Id = 42,
                            Bio = "King Crimson is a British prog rock band whose music pushed the boundaries of rock with experimental elements.",
                            Image = "https://www.rollingstone.com/wp-content/uploads/2019/09/KingCrimson-1.jpg?w=1581&h=1054&crop=1",
                            Name = "King Crimson"
                        },
                        new
                        {
                            Id = 43,
                            Bio = "Ludwig van Beethoven was a German composer and pianist whose work marked the transition between the Classical and Romantic eras.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg/1200px-Joseph_Karl_Stieler%27s_Beethoven_mit_dem_Manuskript_der_Missa_solemnis.jpg",
                            Name = "Ludwig van Beethoven"
                        },
                        new
                        {
                            Id = 44,
                            Bio = "Mozart was a prolific and influential composer of the Classical era known for his symphonies, concertos, and operas.",
                            Image = "https://cdn.britannica.com/35/74835-050-F0B71060/canvas-oil-Wolfgang-Amadeus-Mozart-Barbara-Krafft-1819.jpg",
                            Name = "Wolfgang Amadeus Mozart"
                        },
                        new
                        {
                            Id = 45,
                            Bio = "Bach was a German composer and musician whose compositions are considered masterpieces of Baroque music.",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/6/6a/Johann_Sebastian_Bach.jpg",
                            Name = "Johann Sebastian Bach"
                        });
                });

            modelBuilder.Entity("Limeify.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Relaxing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Classics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Workout"
                        });
                });

            modelBuilder.Entity("Limeify.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Americana"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 8,
                            Name = "R&B"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Alternative"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Punk"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Emo"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Shoegaze"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Math Rock"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Prog Rock"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Classical"
                        });
                });

            modelBuilder.Entity("Limeify.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Playlists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoJpfC3FIYyvcvdKVu0C7aCgqPG9N8EnnfLA&s",
                            Name = "Chill Vibes",
                            Uid = "C0wunKp1sIQRM9YR48JnQPlNXt91"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Image = "https://i1.sndcdn.com/artworks-myKVvYfZpg0PzyNa-ZUliJQ-t500x500.jpg",
                            Name = "Party Hits",
                            Uid = "C0wunKp1sIQRM9YR48JnQPlNXt92"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Image = "https://i1.sndcdn.com/artworks-000223861579-icm151-t500x500.jpg",
                            Name = "Throwback Classics",
                            Uid = "C0wunKp1sIQRM9YR48JnQPlNXt93"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSASIn6nOKM53C64poBVRru1Cc-oONhdTUiw&s",
                            Name = "Indie Discoveries",
                            Uid = "C0wunKp1sIQRM9YR48JnQPlNXt94"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Image = "https://www.funslurp.com/images/baby-buff-1.jpg",
                            Name = "Workout Energy",
                            Uid = "C0wunKp1sIQRM9YR48JnQPlNXt95"
                        });
                });

            modelBuilder.Entity("Limeify.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            ArtistId = 1,
                            GenreId = 1,
                            Length = 418,
                            Name = "Let It Happen"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            ArtistId = 2,
                            GenreId = 1,
                            Length = 257,
                            Name = "Harmony Hall"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            ArtistId = 3,
                            GenreId = 1,
                            Length = 265,
                            Name = "Kyoto"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 4,
                            ArtistId = 4,
                            GenreId = 2,
                            Length = 203,
                            Name = "Beer Never Broke My Heart"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 5,
                            ArtistId = 5,
                            GenreId = 2,
                            Length = 228,
                            Name = "Cry Pretty"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 6,
                            ArtistId = 6,
                            GenreId = 2,
                            Length = 194,
                            Name = "Butterflies"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 7,
                            ArtistId = 7,
                            GenreId = 3,
                            Length = 265,
                            Name = "Cover Me Up"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 8,
                            ArtistId = 8,
                            GenreId = 3,
                            Length = 223,
                            Name = "I and Love and You"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 9,
                            ArtistId = 9,
                            GenreId = 3,
                            Length = 268,
                            Name = "The Joke"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 10,
                            ArtistId = 10,
                            GenreId = 4,
                            Length = 219,
                            Name = "Shake It Off"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 11,
                            ArtistId = 11,
                            GenreId = 4,
                            Length = 182,
                            Name = "7 rings"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 12,
                            ArtistId = 12,
                            GenreId = 4,
                            Length = 183,
                            Name = "Don't Start Now"
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 13,
                            ArtistId = 13,
                            GenreId = 5,
                            Length = 331,
                            Name = "Enter Sandman"
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 14,
                            ArtistId = 14,
                            GenreId = 5,
                            Length = 240,
                            Name = "The Trooper"
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 15,
                            ArtistId = 15,
                            GenreId = 5,
                            Length = 309,
                            Name = "Duality"
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 16,
                            ArtistId = 16,
                            GenreId = 6,
                            Length = 217,
                            Name = "Alright"
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 17,
                            ArtistId = 17,
                            GenreId = 6,
                            Length = 254,
                            Name = "In My Feelings"
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 18,
                            ArtistId = 18,
                            GenreId = 6,
                            Length = 261,
                            Name = "No Role Modelz"
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 19,
                            ArtistId = 19,
                            GenreId = 7,
                            Length = 220,
                            Name = "99 Problems"
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 20,
                            ArtistId = 20,
                            GenreId = 7,
                            Length = 237,
                            Name = "Super Bass"
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 21,
                            ArtistId = 21,
                            GenreId = 7,
                            Length = 259,
                            Name = "Bodak Yellow"
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 22,
                            ArtistId = 22,
                            GenreId = 8,
                            Length = 232,
                            Name = "Formation"
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 23,
                            ArtistId = 23,
                            GenreId = 8,
                            Length = 200,
                            Name = "Blinding Lights"
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 24,
                            ArtistId = 24,
                            GenreId = 8,
                            Length = 223,
                            Name = "Nikes"
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 25,
                            ArtistId = 25,
                            GenreId = 9,
                            Length = 258,
                            Name = "Karma Police"
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 26,
                            ArtistId = 26,
                            GenreId = 9,
                            Length = 221,
                            Name = "Mr. Brightside"
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 27,
                            ArtistId = 27,
                            GenreId = 9,
                            Length = 229,
                            Name = "The Suburbs"
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 28,
                            ArtistId = 28,
                            GenreId = 10,
                            Length = 143,
                            Name = "Blitzkrieg Bop"
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 29,
                            ArtistId = 29,
                            GenreId = 10,
                            Length = 195,
                            Name = "Basket Case"
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 30,
                            ArtistId = 30,
                            GenreId = 10,
                            Length = 210,
                            Name = "London Calling"
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 31,
                            ArtistId = 31,
                            GenreId = 11,
                            Length = 278,
                            Name = "Welcome to the Black Parade"
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 32,
                            ArtistId = 32,
                            GenreId = 11,
                            Length = 222,
                            Name = "The Boy Who Blocked His Own Shot"
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 33,
                            ArtistId = 33,
                            GenreId = 11,
                            Length = 210,
                            Name = "Sugar, We're Goin Down"
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 34,
                            ArtistId = 34,
                            GenreId = 12,
                            Length = 230,
                            Name = "Only Shallow"
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 35,
                            ArtistId = 35,
                            GenreId = 12,
                            Length = 216,
                            Name = "Alison"
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 36,
                            ArtistId = 36,
                            GenreId = 12,
                            Length = 263,
                            Name = "Vapour Trail"
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 37,
                            ArtistId = 37,
                            GenreId = 13,
                            Length = 213,
                            Name = "Never Meant"
                        },
                        new
                        {
                            Id = 38,
                            AlbumId = 38,
                            ArtistId = 38,
                            GenreId = 13,
                            Length = 220,
                            Name = "Goodbye"
                        },
                        new
                        {
                            Id = 39,
                            AlbumId = 39,
                            ArtistId = 39,
                            GenreId = 13,
                            Length = 192,
                            Name = "Catastrophe"
                        },
                        new
                        {
                            Id = 40,
                            AlbumId = 40,
                            ArtistId = 40,
                            GenreId = 14,
                            Length = 414,
                            Name = "Time"
                        },
                        new
                        {
                            Id = 41,
                            AlbumId = 41,
                            ArtistId = 41,
                            GenreId = 14,
                            Length = 408,
                            Name = "Roundabout"
                        },
                        new
                        {
                            Id = 42,
                            AlbumId = 42,
                            ArtistId = 42,
                            GenreId = 14,
                            Length = 420,
                            Name = "21st Century Schizoid Man"
                        },
                        new
                        {
                            Id = 43,
                            AlbumId = 43,
                            ArtistId = 43,
                            GenreId = 15,
                            Length = 4800,
                            Name = "Symphony No. 9 in D minor, Op. 125"
                        },
                        new
                        {
                            Id = 44,
                            AlbumId = 44,
                            ArtistId = 44,
                            GenreId = 15,
                            Length = 3000,
                            Name = "The Magic Flute, K. 620"
                        },
                        new
                        {
                            Id = 45,
                            AlbumId = 45,
                            ArtistId = 45,
                            GenreId = 15,
                            Length = 230,
                            Name = "Prelude and Fugue in C major, BWV 846"
                        });
                });

            modelBuilder.Entity("Limeify.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Artist")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = false,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            Image = "https://example.com/images/john_doe.png",
                            LastName = "Doe",
                            Uid = "C0wunKp1sIQRM9YR48JnQPlNXt92"
                        },
                        new
                        {
                            Id = 2,
                            Artist = false,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            Image = "https://example.com/images/jane_smith.png",
                            LastName = "Smith",
                            Uid = "D1zpqWr2bJUPO7YP39LkWPqMYu64"
                        },
                        new
                        {
                            Id = 3,
                            Artist = false,
                            Email = "alice.brown@example.com",
                            FirstName = "Alice",
                            Image = "https://example.com/images/alice_brown.png",
                            LastName = "Brown",
                            Uid = "E2fopHs3cIKQM8YS50MjYPmOZr85"
                        },
                        new
                        {
                            Id = 4,
                            Artist = false,
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            Image = "https://example.com/images/bob_johnson.png",
                            LastName = "Johnson",
                            Uid = "F3grqUt4dLKRN9ZT61NkZQqPBr96"
                        },
                        new
                        {
                            Id = 5,
                            Artist = false,
                            Email = "charlie.williams@example.com",
                            FirstName = "Charlie",
                            Image = "https://example.com/images/charlie_williams.png",
                            LastName = "Williams",
                            Uid = "G4hsvVv5eMPRO0AU72OlASrQCr07"
                        });
                });

            modelBuilder.Entity("Limeify.Models.Song", b =>
                {
                    b.HasOne("Limeify.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Limeify.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Limeify.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Limeify.Models.Playlist", null)
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId");

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Limeify.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Limeify.Models.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
